import {
  profileLabels,
  type Artifact,
  type Profile,
  type Vertical,
} from "@/lib/content";

/**
 * Turns a finished session into portable text. Everything here is derived
 * from content.ts data, so exports stay correct as verticals change. The
 * "Claude context pack" is real markdown a user can paste into any Claude
 * conversation to keep producing domain-native work.
 */

/** Strip [[term]] highlight markers for plain-text output. */
const plain = (text: string) => text.replace(/\[\[(.*?)\]\]/g, "$1");

export function artifactToMarkdown(artifact: Artifact): string {
  const lines: string[] = [`## ${artifact.label}`, "", artifact.description, ""];

  switch (artifact.kind) {
    case "emailSequence":
      for (const email of artifact.emails) {
        lines.push(
          `### ${email.day} — ${email.purpose}`,
          `Subject: ${email.subject}`,
          "",
          ...email.body.map((p) => plain(p)),
          ""
        );
      }
      break;
    case "callScript":
      lines.push(`_Scenario: ${plain(artifact.scenario)}_`, "");
      for (const section of artifact.sections) {
        lines.push(`### ${section.heading}`);
        for (const line of section.lines) {
          lines.push(
            line.speaker === "you"
              ? `**You:** ${plain(line.text)}`
              : `> Coaching note: ${plain(line.text)}`
          );
        }
        lines.push("");
      }
      break;
    case "landingPage":
      lines.push(
        `### Hero`,
        `Eyebrow: ${artifact.hero.eyebrow}`,
        `Headline: ${plain(artifact.hero.headline)}`,
        `Subhead: ${plain(artifact.hero.subhead)}`,
        `CTA: ${artifact.hero.cta}`,
        "",
        `### Value props`,
        ...artifact.valueProps.map(
          (vp) => `- **${vp.title}** — ${plain(vp.body)}`
        ),
        ""
      );
      break;
    case "ideas":
      lines.push(
        ...artifact.ideas.map(
          (idea, i) => `${i + 1}. **${idea.title}** — ${idea.angle}`
        ),
        ""
      );
      break;
  }

  return lines.join("\n");
}

/**
 * The full session export: who the user is, what the role knows, what the
 * simulation taught, and every produced artifact.
 */
export function buildClaudeContext(
  vertical: Vertical,
  profile: Profile
): string {
  const lines: string[] = [
    `# Domain context pack: ${vertical.industry} — ${vertical.role}`,
    "",
    "Generated by Method Marketing after a learn → simulate → produce session.",
    "Use this as context when producing marketing for this audience.",
    "",
    `## Who I am`,
    profileLabels(vertical.config, profile)
      .map((l) => `- ${l}`)
      .join("\n"),
    "",
    `## The role`,
  ];

  for (const card of vertical.lesson.cards) {
    switch (card.kind) {
      case "terms":
        lines.push(`### Vocabulary (use it naturally, never explain it)`);
        for (const t of card.terms) {
          lines.push(`- **${t.term}** — ${t.definition} ${t.whyItMatters}`);
        }
        lines.push("");
        break;
      case "pressures":
        lines.push(`### What this audience is measured on`);
        for (const p of card.pressures) {
          lines.push(`- **${p.title}** — ${p.body}`);
        }
        lines.push("");
        break;
      default:
        break;
    }
  }

  lines.push(
    `### The simulation's lesson`,
    plain(vertical.outcomes.balanced.coaching),
    "",
    `# Artifacts`,
    ""
  );

  for (const artifact of vertical.payoff.toolkit.artifacts) {
    lines.push(artifactToMarkdown(artifact));
  }

  return lines.join("\n");
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function downloadMarkdown(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
